name: flutter_start_02
description: Flutter Start 002.

version: 1.0.0+4

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/icon/palm.png"
  image_path_ios: "assets/icon/palm.png"
  android: false # can specify file name here e.g. "ic_launcher" / change android sdk
  ios: true
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/icon/palm.png"
  adaptive_icon_background: "#0175C2"

flutter:
  uses-material-design: true
